Web/NineJoke.Web/Areas/Administration/ViewModels/Report/ReportListingModel.cs
namespace NineJoke.Web.Areas.Administration.ViewModels.Report
{
    using System;

    using NineJoke.Data.Models;

    public class ReportListingModel
    {
        public string Id { get; set; }

        public string Reason { get; set; }

        public string PostId { get; set; }

        public string PostTitle { get; set; }

        public string UploaderId { get; set; }

        public string UploaderName { get; set; }

        public string ReporterId { get; set; }

        public string ReporterName { get; set; }

        public DateTime CreatedOn { get; set; }
    }
}

Web/NineJoke.Web/Areas/Administration/Controllers/ReportController.cs
namespace NineJoke.Web.Areas.Administration.Controllers
{
    using System.Linq;

    using Microsoft.AspNetCore.Mvc;
    using NineJoke.Services;
    using NineJoke.Web.Areas.Administration.ViewModels.Report;

    public class ReportController : AdministrationController
    {
        private readonly IReportService reportService;

        public ReportController(IReportService reportService)
        {
            this.reportService = reportService;
        }

        public IActionResult ReportList()
        {
            var viewModel = this.reportService.GetAll().Select(x => new ReportListingModel
            {
                Id = x.Id,
                Reason = x.Reason,
                PostId = x.PostId,
                PostTitle = x.Post.Title,
                UploaderId = x.UploaderId,
                UploaderName = x.Uploader.UserName,
                ReporterId = x.ReporterId,
                ReporterName = x.Reporter.UserName,
                CreatedOn = x.CreatedOn,
            }).ToList();

            return this.View(viewModel);
        }

        public IActionResult Delete(string id)
        {
            this.reportService.DeleteReport(id);

            return this.RedirectToAction("ReportList");
        }

        public IActionResult DeleteAll(string id)
        {
            this.reportService.DeleteAllReports();

            return this.RedirectToAction("ReportList");
        }
    }
}

Web/NineJoke.Web/Controllers/PostController.cs
namespace NineJoke.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;

    using NineJoke.Common;
    using NineJoke.Data.Models;
    using NineJoke.Services;
    using NineJoke.Web.InputModels;
    using NineJoke.Web.ViewModels;

    public class PostController : BaseController
    {
        private readonly IPostService postService;
        private readonly IImageService imageService;
        private readonly ICategoryService categoryService;
        private readonly IUserService userService;
        private readonly ICommentService commentService;
        private readonly IVoteService voteService;

        public PostController(
            IPostService postService,
            IImageService imageService,
            ICategoryService categoryService,
            IUserService userService,
            ICommentService commentService,
            IVoteService voteService)
        {
            this.postService = postService;
            this.imageService = imageService;
            this.categoryService = categoryService;
            this.userService = userService;
            this.commentService = commentService;
            this.voteService = voteService;
        }

        public IActionResult PostDetails(string id, string sortType)
        {
            var user = this.userService.GetUserByName(this.User.Identity.Name);
            var post = this.postService.GetPostById(id);
            var voted = 0;

            if (post == null)
            {
                return this.View("MissingPost");
            }

            if (user != null)
            {
                voted = this.voteService.CheckPostVote(post.Id, user.Id);
            }

            var model = new PostDetailsViewModel
            {
                Id = post.Id,
                Title = post.Title,
                Uploader = post.User.UserName,
                CreatedOn = post.CreatedOn,
                FilePath = post.FilePath,
                Description = post.Description,
                CategoryName = post.Category.Name,
                VoteCount = post.VoteCount,
                Voted = voted,
                CommentCount = post.CommentCount,
            };

            if (sortType == null || sortType.Contains(SortType.Popular.ToString()))
            {
                model.Comments = post.Comments.Select(x => new CommentsViewModel
                {
                    Id = x.Id,
                    Content = x.Content,
                    VoteCount = x.VoteCount,
                    CreatedOn = x.CreatedOn,
                    UserId = x.UserId,
                    UserName = x.User.UserName,
                    PostId = x.PostId,
                }).OrderByDescending(x => x.VoteCount).ToList();
            }
            else if (sortType.Contains(SortType.New.ToString()))
            {
                model.Comments = post.Comments.Select(x => new CommentsViewModel
                {
                    Id = x.Id,
                    Content = x.Content,
                    VoteCount = x.VoteCount,
                    CreatedOn = x.CreatedOn,
                    UserId = x.UserId,
                    UserName = x.User.UserName,
                    PostId = x.PostId,
                }).OrderBy(x => x.CreatedOn).ToList();
            }

            if (user != null)
            {
                for (int i = 0; i < model.Comments.Count(); i++)
                {
                    model.Comments[i].Voted = this.voteService.CheckCommentVote(model.Comments[i].Id, user.Id);
                }
            }

            return this.View(model);
        }

        [Authorize]
        public IActionResult Create()
        {
            var allCategories = this.categoryService.GetAll();

            var categories = allCategories.Select(x => new SelectListItem
            {
                Value = x.Name,
                Text = x.Name,
            }).ToList();

            var model = new PostInputModel { Categories = categories };

            return this.View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(PostInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                var allCategories = this.categoryService.GetAll();

                var categories = allCategories.Select(x => new SelectListItem
                {
                    Value = x.Name,
                    Text = x.Name,
                }).ToList();

                var modelList = new PostInputModel { Categories = categories };

                return this.View(modelList);
            }

            var category = this.categoryService.GetCategoryByName(model.Category);

            var user = this.userService.GetUserByName(this.User.Identity.Name);

            var post = new Post
            {
                Title = model.Title,
                Description = model.Description,
                CreatedOn = DateTime.Now,
                Category = category,
                User = user,
            };

            this.postService.CreatePost(post);

            if (model.Image != null)
            {
                var imageUrl = await this.imageService.UploadImage(model.Image, GlobalConstants.POST_PATH_TEMPLATE, post.Title, post.Id);

                this.postService.AddImageUrl(post.Id, imageUrl);
            }

            return this.Redirect("/");
        }

        [Authorize]
        [HttpPost]
        public IActionResult AddComment([FromBody] CommentInputModel model)
        {
            var currentUser = this.userService.GetUserByName(this.User.Identity.Name);

            var comment = new Comment
            {
                Content = model.Content,
                UserId = currentUser.Id,
                PostId = model.Id,
                CreatedOn = DateTime.Now,
            };

            this.commentService.CreateComment(comment);
            return new JsonResult(model);
        }

        [Authorize]
        [HttpPost]
        public IActionResult VoteComment([FromBody] VoteInputModel model)
        {
            var currentUser = this.userService.GetUserByName(this.User.Identity.Name);
            var comment = this.commentService.GetById(model.Id);
            var userVote = this.voteService.GetVoteCommentById(comment.Id, currentUser.Id);

            if (model.VoteDown != model.VoteUp && userVote == null)
            {
                var vote = new VoteComment
                {
                    CommentId = model.Id,
                    UserId = currentUser.Id,
                };

                if (model.VoteUp == true)
                {
                    vote.UpOrDown = true;
                }
                else if (model.VoteDown == true)
                {
                    vote.UpOrDown = false;
                }

                this.voteService.CreateCommentVote(vote);
            }
            else if (model.VoteDown != model.VoteUp && userVote != null)
            {
                this.voteService.ChangeCommentVote(userVote, model.VoteUp);
            }
            else if (model.VoteDown == model.VoteUp && userVote != null)
            {
                this.voteService.DeleteCommentVote(userVote);
            }

            return new JsonResult(comment.VoteCount);
        }

        [Authorize]
        [HttpPost]
        public IActionResult VotePost([FromBody] VoteInputModel model)
        {
            var currentUser = this.userService.GetUserByName(this.User.Identity.Name);
            var post = this.postService.GetPostById(model.Id);
            var userVote = this.voteService.GetVotePostById(post.Id, currentUser.Id);

            if (model.VoteDown != model.VoteUp && userVote == null)
            {
                var vote = new VotePost
                {
                    PostId = model.Id,
                    UserId = currentUser.Id,
                };

                if (model.VoteUp == true)
                {
                    vote.UpOrDown = true;
                }
                else if (model.VoteDown == true)
                {
                    vote.UpOrDown = false;
                }

                this.voteService.CreatePostVote(vote);
            }
            else if (model.VoteDown != model.VoteUp && userVote != null)
            {
                this.voteService.ChangePostVote(userVote, model.VoteUp);
            }
            else if (model.VoteDown == model.VoteUp && userVote != null)
            {
                this.voteService.DeletePostVote(userVote);
            }

            return new JsonResult(post.VoteCount.ToString());
        }

        [Authorize]
        public IActionResult DeleteComment(string id)
        {
            this.commentService.DeleteComment(id);

            return this.RedirectToAction("UserComments", "User");
        }

        [Authorize]
        public IActionResult Edit(string id)
        {
            var post = this.postService.GetPostById(id);

            var allCategories = this.categoryService.GetAll();

            var categories = allCategories.Select(x => new SelectListItem
            {
                Value = x.Name,
                Text = x.Name,
            }).ToList();

            var model = new PostInputModel
            {
                Id = post.Id,
                Title = post.Title,
                Description = post.Description,
                Categories = categories,
            };

            return this.View(model);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(PostInputModel viewModel)
        {
            this.postService.EditPost(viewModel.Category, viewModel.Title, viewModel.Description, viewModel.Id);

            return this.RedirectToAction("UserPosts", "User");
        }

        [Authorize]

Web/NineJoke.Web/Controllers/ReportController.cs
namespace NineJoke.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using NineJoke.Services;
    using NineJoke.Web.InputModels;

    public class ReportController : BaseController
    {
        private readonly IPostService postService;
        private readonly IUserService userService;
        private readonly IReportService reportService;

        public ReportController(IPostService postService, IUserService userService, IReportService reportService)
        {
            this.postService = postService;
            this.userService = userService;
            this.reportService = reportService;
        }

        [Authorize]
        public IActionResult ReportPost()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult ReportPost(ReportInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var post = this.postService.GetPostById(inputModel.Id);
            var reporter = this.userService.GetUserByName(this.User.Identity.Name);

            this.reportService.CreateReport(inputModel.ReportReason, post.Id, post.UserId, reporter.Id);

            return this.RedirectToAction("Index", "Home");
        }
    }
}

Web/NineJoke.Web/Areas/Administration/Views/Report/ReportList.cshtml
@{
    int i = 0;
}

<style>

    /* The Modal (background) */
    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        padding-top: 100px; /* Location of the box */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }

    /* Modal Content */
    .modal-content {
        background-color: #fefefe;
        margin: auto;
        padding: 20px;
        border: 1px solid #888;
        width: 40%;
    }

    /* The Close Button */
    .close {
        color: #aaaaaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

        .close:hover,
        .close:focus {
            color: #000;
            text-decoration: none;
            cursor: pointer;
        }
</style>


<div align="center">
    <table class="table table-hover">
        <thead>
            <tr class="row">
                <th scope="col" class="col-lg-2">Post Name</th>
                <th scope="col" class="col-lg-2">Uploaded by</th>
                <th scope="col" class="col-lg-2">Reported by</th>
                <th scope="col" class="col-lg-2">Reported on</th>
                <th scope="col" class="col-lg-3" align="right"><a asp-controller="Report" asp-action="DeleteAll" class="btn btn-primary">Ignore all reports</a></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var report in Model)
            {

                <tr class="row">
                    <td class="col-lg-2">@report.PostTitle</td>
                    <td class="col-lg-2">@report.UploaderName</td>
                    <td class="col-lg-2">@report.ReporterName</td>
                    <td class="col-lg-2">@report.CreatedOn</td>
                    <td class="col-lg-3">
                        <div class="button-holder">
                            <div style="display: none;"><p id="@i">@report.Reason</p></div>
                            <button onclick="@("buttonFunc('"+i+"')")" class="btn btn-primary">Reason</button>
                            <a asp-controller="Post" asp-action="PostDetails" asp-route-id="@report.PostId" class="btn btn-primary">Go to post</a>
                            <a asp-controller="Report" asp-action="Delete" asp-route-id="@report.Id" class="btn btn-primary">Ignore</a>
                        </div>
                    </td>
                </tr>
                i = i + 1;
            }
        </tbody>
    </table>
</div>

<div id="myModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <p id="toChange"></p>
    </div>
</div>

<script>
    var modal = document.getElementById("myModal");
    var ptc = document.getElementById("toChange");
    var span = document.getElementsByClassName("close")[0];

    function buttonFunc(elem) {
        modal.style.display = "block";
        var p = document.getElementById(elem);
        ptc.innerHTML = p.innerHTML;
    }
    
    span.onclick = function () {
        modal.style.display = "none";
    }

    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>