Web/NineJoke.Web/Areas/Administration/Controllers/CategoryController.cs
namespace NineJoke.Web.Areas.Administration.Controllers
{
    using System.Linq;

    using Microsoft.AspNetCore.Mvc;

    using NineJoke.Services;
    using NineJoke.Web.Areas.Administration.InputModel.Category;
    using NineJoke.Web.Areas.Administration.ViewModels.Category;

    public class CategoryController : AdministrationController
    {
        private readonly ICategoryService categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public IActionResult CategoryList()
        {
            var viewModel = this.categoryService.GetAll().Select(x => new CategoryListingModel
            {
                Id = x.Id,
                Name = x.Name,
                Popularity = x.Popularity,
            }).ToList().OrderByDescending(x => x.Name);

            return this.View(viewModel);
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Create(CreateCategoryInputModel viewModel)
        {
            this.categoryService.CreateCategory(viewModel.Name);

            return this.RedirectToAction("CategoryList");
        }

        public IActionResult Edit(string id)
        {
            var category = this.categoryService.GetCategoryById(id);

            var model = new CreateCategoryInputModel
            {
                Id = category.Id,
                Name = category.Name,
            };

            return this.View(model);
        }

        [HttpPost]
        public IActionResult Edit(CreateCategoryInputModel viewModel)
        {
            var category = this.categoryService.GetCategoryById(viewModel.Id);

            this.categoryService.EditCategory(viewModel.Name, viewModel.Id);

            return this.RedirectToAction("CategoryList");
        }

        public IActionResult Delete(string id)
        {
            var category = this.categoryService.GetCategoryById(id);

            var model = new CreateCategoryInputModel
            {
                Id = category.Id,
                Name = category.Name,
            };

            return this.View(model);
        }

        [HttpPost]
        public IActionResult Delete(CreateCategoryInputModel viewModel)
        {
            this.categoryService.DeleteCategory(viewModel.Id);

            return this.RedirectToAction("CategoryList");
        }
    }
}

Web/NineJoke.Web/Controllers/ReportController.cs
namespace NineJoke.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using NineJoke.Services;
    using NineJoke.Web.InputModels;

    public class ReportController : BaseController
    {
        private readonly IPostService postService;
        private readonly IUserService userService;
        private readonly IReportService reportService;

        public ReportController(IPostService postService, IUserService userService, IReportService reportService)
        {
            this.postService = postService;
            this.userService = userService;
            this.reportService = reportService;
        }

        [Authorize]
        public IActionResult ReportPost()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult ReportPost(ReportInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var post = this.postService.GetPostById(inputModel.Id);
            var reporter = this.userService.GetUserByName(this.User.Identity.Name);

            this.reportService.CreateReport(inputModel.ReportReason, post.Id, post.UserId, reporter.Id);

            return this.RedirectToAction("Index", "Home");
        }
    }
}

Web/NineJoke.Web/Controllers/UserController.cs
namespace NineJoke.Web.Controllers
{
    using System.Linq;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using NineJoke.Services;
    using NineJoke.Web.ViewModels;

    public class UserController : BaseController
    {
        private readonly IPostService postService;
        private readonly ICommentService commentService;

        public UserController(IPostService postService, ICommentService commentService)
        {
            this.postService = postService;
            this.commentService = commentService;
        }

        [Authorize]
        public IActionResult UserPosts()
        {
            string name = this.User.Identity.Name;

            var viewModel = this.postService.GetPostsByUserName(name).Select(x => new PostViewModel
            {
                Id = x.Id,
                CreatedOn = x.CreatedOn,
                Title = x.Title,
                FilePath = x.FilePath,
                CategoryName = x.Category.Name,
                Description = x.Description,
                VoteCount = x.VoteCount,
                CommentCount = x.CommentCount,
            }).ToList().OrderByDescending(x => x.CreatedOn);

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult UserComments()
        {
            string name = this.User.Identity.Name;

            var viewModel = this.commentService.GetCommentsByUserName(name).Select(x => new CommentsViewModel
            {
                Id = x.Id,
                Content = x.Content,
                VoteCount = x.VoteCount,
                CreatedOn = x.CreatedOn,
                UserId = x.UserId,
                UserName = x.User.UserName,
                PostId = x.PostId,
            }).ToList().OrderByDescending(x => x.CreatedOn);

            return this.View(viewModel);
        }
    }
}

Web/NineJoke.Web/Views/Shared/_CategoryOptions.cshtml
@{
    var Id = Url.ActionContext.RouteData.Values;
}

<style>
    .vertical-menu {
        width: 200px;
    }

        .vertical-menu a {
            background-color: white;
            color: black;
            display: block;
            padding: 12px;
            text-decoration: none;
        }

            .vertical-menu a:hover {
                background-color: #ccc;
            }


            .vertical-menu a.active {
                background-color: #1542ef;
                color: white;
            }
</style>

<div style="float:left;">
    <div class="vertical-menu">
        @if (Model.SortType == "Popular")
        {
            <a asp-controller="Home" asp-action="Index" asp-route-sort="Popular" style="background-color: #bcbcbc;">Popular</a>
        }
        else
        {
            <a asp-controller="Home" asp-action="Index" asp-route-sort="Popular" id="Popular">Popular</a>
        }
        @if (Model.SortType == "New")
        {
            <a asp-controller="Home" asp-action="Index" asp-route-sort="New" style="background-color: #bcbcbc;">New</a>
        }
        else
        {
            <a asp-controller="Home" asp-action="Index" asp-route-sort="New" id="New">New</a>
        }
        
        <hr style="border-width: 3px;" />
    </div>

    <div class="vertical-menu mb-5">
        <a href="#" class="active">Categories</a>
        @foreach (var category in Model.Categories)
        {
            if (category.Id.Equals(Id["id"]))
            {
                <a asp-controller="Home" asp-action="Index" asp-route-id="@category.Id" id="@category.Name" style="background-color: #bcbcbc;">@category.Name</a>
            }
            else
            {
                <a asp-controller="Home" asp-action="Index" asp-route-id="@category.Id" id="@category.Name">@category.Name</a>
            }
        }
    </div>
</div>

Web/NineJoke.Web/Views/Shared/_Layout.cshtml
@using NineJoke.Common
@using NineJoke.Data.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - NineJoke</title>

    <environment names="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-0" id="navbar-one">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" asp-route-id="">NineJoke</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
        {
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" id="navbar-two">
                <div class="container">
                    
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <!--<partial name="_LoginPartial" />-->
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administration" asp-controller="Category" asp-action="CategoryList">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administration" asp-controller="Report" asp-action="ReportList">Reports</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        }
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - NineJoke - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment names="Development">
        
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @this.RenderSection("Scripts", required: false)
</body>
</html>

Web/NineJoke.Web/Views/Shared/_UserProfileOptions.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<nav align="center" class="navbar navbar-expand-lg navbar-light pt-0 pb-0">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item nav-link font-weight-bold">
                <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="UserPosts">Posts</a>
            </li>
            <li class="nav-item nav-link font-weight-bold">
                <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="UserComments">Comments</a>
            </li>
        </ul>
    </div>
</nav>

<hr style="border-width: 5px;">